Repository Sparta-iOS-Development-Team-2/TripLog, pull requests merged in 2025-02, with the labels that each got.

#55 [Feat] 모달뷰 검사 옵션 추가
  TripLog/TripLog/Feat-Crois/ModalViewController/View/ModalAmoutView.swift
  TripLog/TripLog/Feat-Crois/ModalViewController/View/ModalDatePicker.swift
  TripLog/TripLog/Feat-Crois/ModalViewController/View/ModalDateView.swift
  TripLog/TripLog/Feat-Crois/ModalViewController/View/ModalTextField.swift
  TripLog/TripLog/Feat-Crois/ModalViewController/View/ModalView.swift
  TripLog/TripLog/Feat-Crois/ModalViewController/View/ModalViewController.swift
  TripLog/TripLog/Feat-Crois/ModalViewController/ViewModel/ModalViewModel.swift
Labels: enhancement

#56 [Fix] 모달뷰 및 런치 스크린 버그 수정
  TripLog/TripLog/Feat-Crois/ModalViewController/View/ModalDatePicker.swift
  TripLog/TripLog/Feat-Crois/ModalViewController/View/ModalDateView.swift
  TripLog/TripLog/Feat-Crois/ModalViewController/View/ModalViewController.swift
  TripLog/TripLog/MainViewController.swift
Labels: bug

#57 [Feat] TabBar 구현
  TripLog/TripLog.xcodeproj/project.pbxproj
  TripLog/TripLog.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  TripLog/TripLog/Feat-Jeff/CashBookList/View/AddCellView.swift
  TripLog/TripLog/Feat-Jeff/CashBookList/View/CashBookListViewController.swift
  TripLog/TripLog/Feat-Jeff/CashBookList/View/ListCollectionViewCell.swift
  TripLog/TripLog/Feat-Jeff/CustomTabBar/View/CustomTabBarController.swift
  TripLog/TripLog/Feat-Jeff/CustomTabBar/View/CustomTabBarView.swift
  TripLog/TripLog/Feat-Jeff/CustomTabBar/ViewModel/CustomTabBarViewModel.swift
  TripLog/TripLog/MainViewController.swift
  TripLog/TripLog/Source/Extension/UIViewStyle+Extension.swift
Labels: enhancement

#59 [Fix] 상세 가계부 탑뷰 리팩토링
  TripLog/TripLog/Feat-Stone/View/ButtonStackView.swift
  TripLog/TripLog/Feat-Stone/View/CustomProgressView.swift
  TripLog/TripLog/Feat-Stone/View/ProgressView.swift
  TripLog/TripLog/Feat-Stone/View/TopProgressView.swift
  TripLog/TripLog/Feat-Stone/View/TopViewController.swift
  TripLog/TripLog/Source/Extension/UIViewGradient+Extension.swift
Labels: enhancement, refactoring

#53 [Feat] CoreData 개선작업
  TripLog/TripLog.xcodeproj/project.pbxproj
  TripLog/TripLog/Application/AppDelegate.swift
  TripLog/TripLog/Application/Hamsik/API&CoreData/Model/CurrencyRate.swift
  TripLog/TripLog/Application/Hamsik/API&CoreData/Network/APIManager.swift
  TripLog/TripLog/Application/Hamsik/API&CoreData/Network/CoreDataManager.swift
  TripLog/TripLog/Application/Hamsik/Extension/CashBookEntity+Ext.swift
  TripLog/TripLog/Application/Hamsik/Extension/CurrencyEntity+Ext.swift
  TripLog/TripLog/Application/Hamsik/Extension/Date+Extension.swift
  TripLog/TripLog/Application/Hamsik/Extension/MyCashBookEntity+Ext.swift
  TripLog/TripLog/Application/Hamsik/Protocol/EntitiesProtocol.swift
  TripLog/TripLog/Application/Hamsik/Utility/APIInfo.swift
  TripLog/TripLog/Application/Hamsik/Utility/AppInfo.swift
  TripLog/TripLog/Application/Hamsik/Utility/Entities.swift
  TripLog/TripLog/Application/TripLog.xcdatamodeld/TripLog.xcdatamodel/contents
  TripLog/TripLog/Source/API&CoreData/Model/CurrencyEntity+CoreDataClass.swift
  TripLog/TripLog/Source/API&CoreData/Model/CurrencyEntity+CoreDataProperties.swift
  TripLog/TripLog/Source/API&CoreData/Network/CoreDataManager.swift
  TripLog/TripLogTests/CoreDataTests.swift
Labels: enhancement

#60 [Feat] Firestore 연결
  .gitignore
  TripLog/TripLog.xcodeproj/project.pbxproj
  TripLog/TripLog.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  TripLog/TripLog/Application/AppDelegate.swift
  TripLog/TripLog/Feat-Hamsik/API&CoreData/Network/FireStoreManager.swift
  TripLog/TripLog/Feat-Hamsik/Extension/CurrencyEntity+Ext.swift
Labels: enhancement

#65 [Feat] 모달뷰 데이터 로직 추가
  TripLog/TripLog.xcodeproj/project.pbxproj
  TripLog/TripLog/Feat-Crois/ModalViewController/Model/ModalViewState.swift
  TripLog/TripLog/Feat-Crois/ModalViewController/Model/TestCashBookData.swift
  TripLog/TripLog/Feat-Crois/ModalViewController/Model/TestModalViewData.swift
  TripLog/TripLog/Feat-Crois/ModalViewController/View/ModalAmountView.swift
  TripLog/TripLog/Feat-Crois/ModalViewController/View/ModalDatePicker.swift
  TripLog/TripLog/Feat-Crois/ModalViewController/View/ModalDateView.swift
  TripLog/TripLog/Feat-Crois/ModalViewController/View/ModalSegmentView.swift
  TripLog/TripLog/Feat-Crois/ModalViewController/View/ModalTextField.swift
  TripLog/TripLog/Feat-Crois/ModalViewController/View/ModalView.swift
  TripLog/TripLog/Feat-Crois/ModalViewController/View/ModalViewController.swift
  TripLog/TripLog/Feat-Crois/ModalViewController/ViewModel/ModalViewModel.swift
  TripLog/TripLog/Feat-Hamsik/API&CoreData/Network/FireStoreManager.swift
  TripLog/TripLog/Feat-Hamsik/Extension/CashBookEntity+Ext.swift
  TripLog/TripLog/Feat-Hamsik/Extension/CurrencyEntity+Ext.swift
Labels: enhancement

#66 🐛 [fix] Save&Fetch 버그 해결
  TripLog/TripLog.xcodeproj/project.pbxproj
  TripLog/TripLog/Feat-Hamsik/Extension/CashBookEntity+Ext.swift
  TripLog/TripLog/Feat-Hamsik/Extension/CurrencyEntity+Ext.swift
  TripLog/TripLog/Feat-Hamsik/Extension/MyCashBookEntity+Ext.swift
  TripLog/TripLog/Feat-Hamsik/Utility/Entities.swift
Labels: bug, enhancement

#61 [ feat ] 탑UI 오늘지출UI 결합 및 모달 연결
  TripLog/TripLog/Feat-Jeff/CustomTabBar/View/CustomTabBarController.swift
  TripLog/TripLog/Feat-Stone/Model/TestDummyData.swift
  TripLog/TripLog/Feat-Stone/Model/TestTodayDummyData.swift
  TripLog/TripLog/Feat-Stone/View/ButtonStackView.swift
  TripLog/TripLog/Feat-Stone/View/CustomProgressView.swift
  TripLog/TripLog/Feat-Stone/View/CustomTableViewCell.swift
  TripLog/TripLog/Feat-Stone/View/TitleDateLabelView.swift
  TripLog/TripLog/Feat-Stone/View/TodayView/ExpenseCell.swift
  TripLog/TripLog/Feat-Stone/View/TodayView/TodayVIewController.swift
  TripLog/TripLog/Feat-Stone/View/TopProgressView.swift
  TripLog/TripLog/Feat-Stone/View/TopViewController.swift
Labels: enhancement

#72 [Feat] 가계부 리스트
  TripLog/TripLog/Feat-Crois/ModalViewController/View/ModalView.swift
  TripLog/TripLog/Feat-Jeff/CashBookList/Model/CashBookListModel.swift
  TripLog/TripLog/Feat-Jeff/CashBookList/View/AddCellView.swift
  TripLog/TripLog/Feat-Jeff/CashBookList/View/CashBookListViewController.swift
  TripLog/TripLog/Feat-Jeff/CashBookList/View/ListCollectionViewCell.swift
  TripLog/TripLog/Feat-Jeff/CashBookList/ViewModel/CashBookListViewModel.swift
Labels: enhancement

#76 [Feat] 코어데이터 구조 개선
  TripLog/TripLog/Application/TripLog.xcdatamodeld/TripLog.xcdatamodel/contents
  TripLog/TripLog/Feat-Crois/ModalViewController/View/ModalViewController.swift
  TripLog/TripLog/Feat-Hamsik/API&CoreData/Network/CoreDataManager.swift
  TripLog/TripLog/Feat-Hamsik/Extension/CashBookEntity+Ext.swift
  TripLog/TripLog/Feat-Hamsik/Extension/CurrencyEntity+Ext.swift
  TripLog/TripLog/Feat-Hamsik/Extension/MyCashBookEntity+Ext.swift
  TripLog/TripLog/Feat-Hamsik/Protocol/EntitiesProtocol.swift
  TripLog/TripLog/Feat-Hamsik/Utility/Entities.swift
Labels: bug, enhancement

#68 [Fix] 다크모드/라이트모드 설정 기억
  TripLog/TripLog/Application/SceneDelegate.swift
  TripLog/TripLog/Feat-Crois/SettingViewController/Model/SettingTableCellModel.swift
  TripLog/TripLog/MainViewController.swift
  TripLog/TripLog/Source/AppHelpers/ThemeManager.swift
Labels: bug

#71 ✨[feat] 캘린더 지출 목록 UI 구현
  TripLog/TripLog/Feat-Jamong/ModalViewController/View/CalendarCustomCell.swift
  TripLog/TripLog/Feat-Jamong/ModalViewController/View/CalendarCustomHeaderView.swift
  TripLog/TripLog/Feat-Jamong/ModalViewController/View/CalendarView.swift
  TripLog/TripLog/Feat-Jamong/ModalViewController/View/CalendarViewController.swift
  TripLog/TripLog/Feat-Jamong/Model/ExpenseModel.swift
  TripLog/TripLog/Feat-Jamong/View/CalendarExpenseView/CalendarExpenseCell.swift
  TripLog/TripLog/Feat-Jamong/View/CalendarExpenseView/CalendarExpenseListHeaderView.swift
  TripLog/TripLog/Feat-Jamong/View/CalendarExpenseView/CalendarExpenseView.swift
  TripLog/TripLog/Feat-Jamong/View/CalendarView/CalendarCustomCell.swift
  TripLog/TripLog/Feat-Jamong/View/CalendarView/CalendarCustomHeaderView.swift
  TripLog/TripLog/Feat-Jamong/View/CalendarView/CalendarView.swift
  TripLog/TripLog/Feat-Jamong/View/CalendarViewController.swift
  TripLog/TripLog/Feat-Jamong/ViewModel/CalendarViewModel.swift
  TripLog/TripLog/Source/Extension/UIFont+Extension.swift
Labels: enhancement

#81 ♻️[refactor] 캘린더 헤더 날짜 변경 기능 리팩토링
  TripLog/TripLog/Feat-Jamong/View/CalendarExpenseView/CalendarExpenseCell.swift
  TripLog/TripLog/Feat-Jamong/View/CalendarExpenseView/CalendarExpenseView.swift
  TripLog/TripLog/Feat-Jamong/View/CalendarView/CalendarCustomCell.swift
  TripLog/TripLog/Feat-Jamong/View/CalendarView/CalendarCustomHeaderView.swift
  TripLog/TripLog/Feat-Jamong/View/CalendarView/CalendarView.swift
  TripLog/TripLog/Feat-Jamong/View/CalendarViewController.swift
  TripLog/TripLog/Feat-Jamong/ViewModel/CalendarViewModel.swift
Labels: refactoring

#79 [Fix] 다크 / 라이트 모드 적용, UI 리팩토링
  TripLog/TripLog/Feat-Jeff/CashBookList/Service/DateFormatModel.swift
  TripLog/TripLog/Feat-Jeff/CashBookList/Service/UpdateTabBarItem.swift
  TripLog/TripLog/Feat-Jeff/CashBookList/View/CashBookListViewController.swift
  TripLog/TripLog/Feat-Jeff/CashBookList/View/ListCollectionViewCell.swift
  TripLog/TripLog/Feat-Jeff/CustomTabBar/View/CustomTabBarController.swift
  TripLog/TripLog/Feat-Jeff/CustomTabBar/View/CustomTabBarView.swift
  TripLog/TripLog/Source/Extension/UIViewStyle+Extension.swift
Labels: bug, enhancement

#83 [Fix] 가계부 리스트에 추가하기 셀 버그 수정
  TripLog/TripLog/Feat-Jeff/CashBookList/Service/UpdateTabBarItem.swift
  TripLog/TripLog/Feat-Jeff/CashBookList/View/AddCellView.swift
  TripLog/TripLog/Feat-Jeff/CashBookList/View/CashBookListViewController.swift
  TripLog/TripLog/Feat-Jeff/CashBookList/View/ListCollectionViewCell.swift
  TripLog/TripLog/Feat-Jeff/CashBookList/ViewModel/CashBookListViewModel.swift
  TripLog/TripLog/Feat-Jeff/CustomTabBar/View/CustomTabBarController.swift
  TripLog/TripLog/Feat-Jeff/CustomTabBar/View/CustomTabBarView.swift
  TripLog/TripLog/Source/Extension/UIViewStyle+Extension.swift
Labels: bug, enhancement

#82 [ Feat ] 탑뷰와 CoreData
  TripLog/TripLog/Feat-Stone/Model/TestSection.swift
  TripLog/TripLog/Feat-Stone/Model/TestTodayDummyData.swift
  TripLog/TripLog/Feat-Stone/View/ButtonStackView.swift
  TripLog/TripLog/Feat-Stone/View/CustomProgressView.swift
  TripLog/TripLog/Feat-Stone/View/CustomTableViewCell.swift
  TripLog/TripLog/Feat-Stone/View/TodayView/ExpenseCell.swift
  TripLog/TripLog/Feat-Stone/View/TodayView/TodayVIewController.swift
  TripLog/TripLog/Feat-Stone/View/TopProgressView.swift
  TripLog/TripLog/Feat-Stone/View/TopViewController.swift
  TripLog/TripLog/Feat-Stone/ViewModel/TodayViewModel.swift
  TripLog/TripLog/Feat-Stone/ViewModel/TopViewModel.swift
  TripLog/TripLog/Source/Extension/UIViewStyle+Extension.swift
Labels: enhancement

#85 [Refactor] 프로젝트 리팩토링
  TripLog/TripLog/Feat-Crois/ModalViewController/View/ModalButtons.swift
  TripLog/TripLog/Feat-Jamong/View/CalendarExpenseView/CalendarExpenseListHeaderView.swift
  TripLog/TripLog/Feat-Jamong/View/CalendarExpenseView/CalendarExpenseView.swift
  TripLog/TripLog/Feat-Jamong/View/CalendarView/CalendarCustomHeaderView.swift
  TripLog/TripLog/Feat-Jamong/View/CalendarView/CalendarView.swift
  TripLog/TripLog/Feat-Jamong/View/CalendarViewController.swift
  TripLog/TripLog/Feat-Jamong/ViewModel/CalendarViewModel.swift
  TripLog/TripLog/Feat-Jeff/CashBookList/View/CashBookListViewController.swift
  TripLog/TripLog/Feat-Stone/View/CustomProgressView.swift
  TripLog/TripLog/Feat-Stone/View/CustomTableViewCell.swift
  TripLog/TripLog/Feat-Stone/View/TodayView/TodayVIewController.swift
  TripLog/TripLog/Feat-Stone/View/TopViewController.swift
  TripLog/TripLog/Feat-Stone/ViewModel/TodayViewModel.swift
Labels: bug, refactoring

#98 [Feat] 캘린더와 CoreData 연결
  TripLog/TripLog/Feat-Jamong/View/CalendarViewController.swift
  TripLog/TripLog/Feat-Jamong/ViewModel/CalendarViewModel.swift
Labels: enhancement

#95 [Refactor] 모달뷰 로직 수정
  TripLog/TripLog/Feat-Crois/ModalViewController/Model/MockDataProtocol.swift
  TripLog/TripLog/Feat-Crois/ModalViewController/Model/ModalConsumptionData.swift
  TripLog/TripLog/Feat-Crois/ModalViewController/Model/ModalViewManager.swift
  TripLog/TripLog/Feat-Crois/ModalViewController/Model/ModalViewState.swift
  TripLog/TripLog/Feat-Crois/ModalViewController/View/ModalView.swift
  TripLog/TripLog/Feat-Crois/ModalViewController/View/ModalViewController.swift
  TripLog/TripLog/Feat-Jeff/CashBookList/View/CashBookListViewController.swift
  TripLog/TripLog/Feat-Jeff/CustomTabBar/View/CustomTabBarController.swift
  TripLog/TripLog/Feat-Stone/View/TodayView/TodayVIewController.swift
Labels: refactoring

#96 [Feat] Firestore&CoreData 동기화
  TripLog/TripLog/Feat-Hamsik/API&CoreData/Manager/APIManager.swift
  TripLog/TripLog/Feat-Hamsik/API&CoreData/Manager/CoreDataManager.swift
  TripLog/TripLog/Feat-Hamsik/API&CoreData/Manager/FireStoreManager.swift
  TripLog/TripLog/Feat-Hamsik/API&CoreData/Model/CurrencyRate.swift
  TripLog/TripLog/Feat-Hamsik/Extension/CurrencyEntity+Ext.swift
  TripLog/TripLog/Feat-Hamsik/Utility/HamsikConfig.swift
  TripLog/TripLogTests/CoreDataTests.swift
Labels: enhancement

#97 [Feat] 온보딩 뷰 추가
  TripLog/TripLog/Feat-Crois/OnboardingViewController/OnboardingView.swift
  TripLog/TripLog/Feat-Crois/OnboardingViewController/OnboardingViewController.swift
  TripLog/TripLog/MainViewController.swift
  TripLog/TripLog/Source/Assets/Assets.xcassets/Onboarding/Contents.json
  TripLog/TripLog/Source/Assets/Assets.xcassets/Onboarding/page1.imageset/Contents.json
  TripLog/TripLog/Source/Assets/Assets.xcassets/Onboarding/page1.imageset/Dark Page1.png
  TripLog/TripLog/Source/Assets/Assets.xcassets/Onboarding/page1.imageset/Light Page1 1.png
  TripLog/TripLog/Source/Assets/Assets.xcassets/Onboarding/page1.imageset/Light Page1.png
  TripLog/TripLog/Source/Assets/Assets.xcassets/Onboarding/page2.imageset/Contents.json
  TripLog/TripLog/Source/Assets/Assets.xcassets/Onboarding/page2.imageset/Dark Page2.png
  TripLog/TripLog/Source/Assets/Assets.xcassets/Onboarding/page2.imageset/Light Page2 1.png
  TripLog/TripLog/Source/Assets/Assets.xcassets/Onboarding/page2.imageset/Light Page2.png
  TripLog/TripLog/Source/Assets/Assets.xcassets/Onboarding/page3.imageset/Contents.json
  TripLog/TripLog/Source/Assets/Assets.xcassets/Onboarding/page3.imageset/Dark Page3.png
  TripLog/TripLog/Source/Assets/Assets.xcassets/Onboarding/page3.imageset/Light Page3 1.png
  TripLog/TripLog/Source/Assets/Assets.xcassets/Onboarding/page3.imageset/Light Page3.png
Labels: enhancement

#101 [Feat] 환율정보 예외처리
  TripLog/TripLog/Feat-Hamsik/API&CoreData/Manager/CoreDataManager.swift
  TripLog/TripLog/Feat-Hamsik/API&CoreData/Manager/FireStoreManager.swift
  TripLog/TripLog/Feat-Hamsik/API&CoreData/Manager/SyncManager.swift
  TripLog/TripLog/Feat-Hamsik/Extension/CashBookEntity+Ext.swift
  TripLog/TripLog/Feat-Hamsik/Extension/CurrencyEntity+Ext.swift
  TripLog/TripLog/Feat-Hamsik/Extension/Date+Extension.swift
  TripLog/TripLog/Feat-Hamsik/Extension/MyCashBookEntity+Ext.swift
  TripLog/TripLog/Feat-Hamsik/Protocol/EntitiesProtocol.swift
  TripLog/TripLog/Feat-Hamsik/Utility/CurrencyRateResultType.swift
  TripLog/TripLog/Feat-Hamsik/Utility/HamsikConfig.swift
  TripLog/TripLog/MainViewController.swift
Labels: enhancement

#102 [feat] MyCashBookEntity 계산값 추가
  TripLog/TripLog/Application/TripLog.xcdatamodeld/TripLog.xcdatamodel/contents
  TripLog/TripLog/Feat-Crois/ModalViewController/View/ModalViewController.swift
  TripLog/TripLog/Feat-Hamsik/Extension/MyCashBookEntity+Ext.swift
  TripLog/TripLog/Feat-Hamsik/Utility/Entities.swift
  TripLog/TripLog/Feat-Jamong/ViewModel/CalendarViewModel.swift
  TripLog/TripLog/Feat-Stone/ViewModel/TodayViewModel.swift
Labels: enhancement

#103 [Feat] Popover 기능 추가
  TripLog/TripLog/Feat-Jeff/CashBookList/Service/DateFormatModel.swift
  TripLog/TripLog/Feat-Jeff/CashBookList/View/CashBookListViewController.swift
  TripLog/TripLog/Feat-Jeff/CustomTabBar/View/CustomTabBarController.swift
  TripLog/TripLog/Feat-Jeff/CustomTabBar/View/CustomTabBarView.swift
  TripLog/TripLog/Feat-Jeff/Popover/CalculateDate.swift
  TripLog/TripLog/Feat-Jeff/Popover/PopoverManager.swift
  TripLog/TripLog/Feat-Jeff/Popover/PopoverViewController.swift
  TripLog/TripLog/Source/Extension/UIViewStyle+Extension.swift
Labels: enhancement

#108 [Feat] 캘린더 뷰 및 캘린더 지출목록 기능 구현 완료
  TripLog/TripLog/Feat-Jamong/View/CalendarExpenseView/CalendarExpenseCell.swift
  TripLog/TripLog/Feat-Jamong/View/CalendarExpenseView/CalendarExpenseListHeaderView.swift
  TripLog/TripLog/Feat-Jamong/View/CalendarExpenseView/CalendarExpenseView.swift
  TripLog/TripLog/Feat-Jamong/View/CalendarView/CalendarView.swift
  TripLog/TripLog/Feat-Jamong/View/CalendarViewController.swift
  TripLog/TripLog/Feat-Jamong/ViewModel/CalendarViewModel.swift
Labels: enhancement

#105 [Feat] 모달뷰 지출 내역 키보드 타입 수정
  TripLog/TripLog/Feat-Crois/ModalViewController/Model/ModalConsumptionData.swift
  TripLog/TripLog/Feat-Crois/ModalViewController/Model/ModalViewState.swift
  TripLog/TripLog/Feat-Crois/ModalViewController/View/ModalAmountView.swift
  TripLog/TripLog/Feat-Crois/ModalViewController/View/ModalDatePicker.swift
  TripLog/TripLog/Feat-Crois/ModalViewController/View/ModalDateView.swift
  TripLog/TripLog/Feat-Crois/ModalViewController/View/ModalTextField.swift
  TripLog/TripLog/Feat-Crois/ModalViewController/View/ModalView.swift
  TripLog/TripLog/Feat-Crois/ModalViewController/View/ModalViewController.swift
  TripLog/TripLog/Feat-Crois/ModalViewController/ViewModel/ModalViewModel.swift
  TripLog/TripLog/Source/Extension/Double+Extension.swift
Labels: refactoring

#109 [ Feat ] 탑뷰 UI 구조 리팩토링 및 로직 추가
  TripLog/TripLog/Feat-Stone/Model/CurrencyFormatter.swift
  TripLog/TripLog/Feat-Stone/View/CustomProgressView.swift
  TripLog/TripLog/Feat-Stone/View/CustomTableViewCell.swift
  TripLog/TripLog/Feat-Stone/View/TodayView/ExpenseCell.swift
  TripLog/TripLog/Feat-Stone/View/TodayView/TodayVIewController.swift
  TripLog/TripLog/Feat-Stone/View/TopView/CustomButtonStackView.swift
  TripLog/TripLog/Feat-Stone/View/TopView/CustomProgressView.swift
  TripLog/TripLog/Feat-Stone/View/TopView/TitleDateLabelView.swift
  TripLog/TripLog/Feat-Stone/View/TopView/TopProgressView.swift
  TripLog/TripLog/Feat-Stone/View/TopView/TopViewController.swift
  TripLog/TripLog/Feat-Stone/View/TopView/TripLogSummaryView.swift
  TripLog/TripLog/Feat-Stone/View/TopView/TripSwitcherView.swift
  TripLog/TripLog/Feat-Stone/View/TopViewController.swift
  TripLog/TripLog/Feat-Stone/ViewModel/TodayViewModel.swift
  TripLog/TripLog/Feat-Stone/ViewModel/TopViewModel.swift
  TripLog/TripLog/Source/Extension/String+Extension.swift
Labels: enhancement

#111 [Refactor] 캘린더 amount값을 caculatedAmount로 리팩토링
  TripLog/TripLog/Application/TripLog.xcdatamodeld/TripLog.xcdatamodel/contents
  TripLog/TripLog/Feat-Hamsik/Extension/MyCashBookEntity+Ext.swift
  TripLog/TripLog/Feat-Jamong/View/CalendarExpenseView/CalendarExpenseCell.swift
  TripLog/TripLog/Feat-Jamong/View/CalendarExpenseView/CalendarExpenseListHeaderView.swift
  TripLog/TripLog/Feat-Jamong/View/CalendarExpenseView/CalendarExpenseView.swift
  TripLog/TripLog/Feat-Jamong/View/CalendarViewController.swift
  TripLog/TripLog/Feat-Jamong/ViewModel/CalendarViewModel.swift
Labels: refactoring

#113 [fix] 통화코드 수정
  TripLog/TripLog/Feat-Crois/ModalViewController/Model/Currencys.swift
Labels: bug

#115 [Refactor] 프로젝트 리팩토링
  TripLog/TripLog/Feat-Jamong/View/CalendarExpenseView/CalendarExpenseCell.swift
  TripLog/TripLog/Feat-Jamong/View/CalendarView/CalendarCustomHeaderView.swift
  TripLog/TripLog/Feat-Jamong/View/CalendarViewController.swift
  TripLog/TripLog/Feat-Jeff/Popover/CalculateDate.swift
  TripLog/TripLog/Feat-Stone/Model/CurrencyFormatter.swift
  TripLog/TripLog/Feat-Stone/View/TodayView/ExpenseCell.swift
  TripLog/TripLog/Feat-Stone/View/TodayView/TodayVIewController.swift
  TripLog/TripLog/Feat-Stone/View/TopView/TitleDateLabelView.swift
  TripLog/TripLog/Feat-Stone/View/TopView/TopProgressView.swift
  TripLog/TripLog/Feat-Stone/View/TopView/TopViewController.swift
  TripLog/TripLog/Feat-Stone/View/TopView/TripLogSummaryView.swift
  TripLog/TripLog/Feat-Stone/ViewModel/TodayViewModel.swift
Labels: refactoring

#119 * ♻️ [refactor] 파일 구조 리팩토링, 안쓰는 주석 부분 삭제
  TripLog/TripLog/Feat-Stone/Model/CashBookSection.swift
  TripLog/TripLog/Feat-Stone/Model/TestDummyData.swift
  TripLog/TripLog/Feat-Stone/Model/TestTodayDummyData.swift
  TripLog/TripLog/Feat-Stone/View/TodayView/ExpenseCell.swift
  TripLog/TripLog/Feat-Stone/View/TodayView/TodayVIewController.swift
  TripLog/TripLog/Feat-Stone/View/TopView/CustomButtonStackView.swift
  TripLog/TripLog/Feat-Stone/View/TopView/CustomProgressView.swift
  TripLog/TripLog/Feat-Stone/View/TopView/TitleDateLabelView.swift
  TripLog/TripLog/Feat-Stone/View/TopView/TopProgressView.swift
  TripLog/TripLog/Feat-Stone/View/TopView/TopViewController.swift
  TripLog/TripLog/Source/Extension/DoubleSymbol+Extension.swift
Labels: refactoring

#136 [ Feat ] 필터 범위 오늘 -> 전체로 확대
  TripLog/TripLog.xcodeproj/xcshareddata/xcschemes/TripLog.xcscheme
  TripLog/TripLog/Resource/Assets/Assets.xcassets/todayViewItem/Contents.json
  TripLog/TripLog/Resource/Assets/Assets.xcassets/todayViewItem/filterIcon.imageset/Contents.json
  TripLog/TripLog/Resource/Assets/Assets.xcassets/todayViewItem/filterIcon.imageset/Frame 1261157332.png
  TripLog/TripLog/Resource/Assets/Assets.xcassets/todayViewItem/filterIcon.imageset/Frame 1261157333.png
  TripLog/TripLog/Resource/Assets/Assets.xcassets/todayViewItem/filterIcon.imageset/KakaoTalk_Photo_2025-02-18-15-27-14.png
  TripLog/TripLog/Source/View/TodayView/ExpenseCell.swift
  TripLog/TripLog/Source/View/TodayView/TodaySectionModel.swift
  TripLog/TripLog/Source/View/TodayView/TodayViewController.swift
  TripLog/TripLog/Source/View/TopView/CustomButtonStackView.swift
  TripLog/TripLog/Source/ViewModel/TodayView/TodayViewModel.swift
Labels: enhancement

#131 ✨ [feat] 미래 날짜 안내 알럿 구현
  TripLog/TripLog/Source/AppHelp/Extension/Date+Ext.swift
  TripLog/TripLog/Source/View/Calendar/CalendarViewController.swift
Labels: enhancement

#139 [Doc] Update README.md
  README.md
Labels: refactoring

#140 [Release] TripLog Ver 1.1.2
  TripLog/TripLog/Resource/Assets/Assets.xcassets/Onboarding/page3.imageset/Contents.json
  TripLog/TripLog/Resource/Assets/Assets.xcassets/Onboarding/page3.imageset/Dark Page33.png
  TripLog/TripLog/Resource/Assets/Assets.xcassets/Onboarding/page3.imageset/Light Page33 1.png
  TripLog/TripLog/Resource/Assets/Assets.xcassets/Onboarding/page3.imageset/Light Page33.png
  TripLog/TripLog/Source/View/Calendar/CalendarViewController.swift
  TripLog/TripLog/Source/View/Calendar/FSCalendarView/CalendarCustomCell.swift
  TripLog/TripLog/Source/View/TabBar/CustomTabBarView.swift
  TripLog/TripLog/Source/View/TodayView/TodayViewController.swift
  TripLog/TripLog/Source/View/TopView/CustomProgressView.swift
Labels: good first issue
