Repository Sparta-iOS-Development-Team-2/TripLog, pull requests merged in 2025-01, with the labels that each got.

#4 🚨[hotFix] 뷰 모델 타입 추상화 추가
  TripLog/TripLog/Source/Assets/Assets.xcassets/AccentColor.colorset/Contents.json
  TripLog/TripLog/Source/Assets/Assets.xcassets/AppIcon.appiconset/Contents.json
  TripLog/TripLog/Source/Assets/Assets.xcassets/Contents.json
  TripLog/TripLog/Source/Assets/ColorAsseets.xcassets/Contents.json
  TripLog/TripLog/Source/Assets/ColorAsseets.xcassets/Dark/Contents.json
  TripLog/TripLog/Source/Assets/ColorAsseets.xcassets/Dark/base.colorset/Contents.json
  TripLog/TripLog/Source/Assets/ColorAsseets.xcassets/Dark/r100.colorset/Contents.json
  TripLog/TripLog/Source/Assets/ColorAsseets.xcassets/Dark/r200.colorset/Contents.json
  TripLog/TripLog/Source/Assets/ColorAsseets.xcassets/Dark/r300.colorset/Contents.json
  TripLog/TripLog/Source/Assets/ColorAsseets.xcassets/Dark/r400.colorset/Contents.json
  TripLog/TripLog/Source/Assets/ColorAsseets.xcassets/Dark/r50.colorset/Contents.json
  TripLog/TripLog/Source/Assets/ColorAsseets.xcassets/Dark/r500.colorset/Contents.json
  TripLog/TripLog/Source/Assets/ColorAsseets.xcassets/Dark/r600.colorset/Contents.json
  TripLog/TripLog/Source/Assets/ColorAsseets.xcassets/Dark/r700.colorset/Contents.json
  TripLog/TripLog/Source/Assets/ColorAsseets.xcassets/Dark/r800.colorset/Contents.json
  TripLog/TripLog/Source/Assets/ColorAsseets.xcassets/Dark/r900.colorset/Contents.json
  TripLog/TripLog/Source/Assets/ColorAsseets.xcassets/Dark/r950.colorset/Contents.json
  TripLog/TripLog/Source/Assets/ColorAsseets.xcassets/Light/Contents.json
  TripLog/TripLog/Source/Assets/ColorAsseets.xcassets/Light/base.colorset/Contents.json
  TripLog/TripLog/Source/Assets/ColorAsseets.xcassets/Light/r100.colorset/Contents.json
  TripLog/TripLog/Source/Assets/ColorAsseets.xcassets/Light/r200.colorset/Contents.json
  TripLog/TripLog/Source/Assets/ColorAsseets.xcassets/Light/r300.colorset/Contents.json
  TripLog/TripLog/Source/Assets/ColorAsseets.xcassets/Light/r400.colorset/Contents.json
  TripLog/TripLog/Source/Assets/ColorAsseets.xcassets/Light/r50.colorset/Contents.json
  TripLog/TripLog/Source/Assets/ColorAsseets.xcassets/Light/r500.colorset/Contents.json
  TripLog/TripLog/Source/Assets/ColorAsseets.xcassets/Light/r600.colorset/Contents.json
  TripLog/TripLog/Source/Assets/ColorAsseets.xcassets/Light/r700.colorset/Contents.json
  TripLog/TripLog/Source/Assets/ColorAsseets.xcassets/Light/r800.colorset/Contents.json
  TripLog/TripLog/Source/Assets/ColorAsseets.xcassets/Light/r900.colorset/Contents.json
  TripLog/TripLog/Source/Assets/ColorAsseets.xcassets/Light/r950.colorset/Contents.json
  TripLog/TripLog/Source/Assets/ColorAsseets.xcassets/Personal/Contents.json
  TripLog/TripLog/Source/Assets/ColorAsseets.xcassets/Personal/dark.colorset/Contents.json
  TripLog/TripLog/Source/Assets/ColorAsseets.xcassets/Personal/light.colorset/Contents.json
  TripLog/TripLog/Source/Assets/ColorAsseets.xcassets/Personal/normal.colorset/Contents.json
  TripLog/TripLog/Source/Extension/UIFont+Extension.swift
  TripLog/TripLog/Source/Fonts/SCDream1.otf
  TripLog/TripLog/Source/Fonts/SCDream2.otf
  TripLog/TripLog/Source/Fonts/SCDream3.otf
  TripLog/TripLog/Source/Fonts/SCDream4.otf
  TripLog/TripLog/Source/Fonts/SCDream5.otf
  TripLog/TripLog/Source/Fonts/SCDream6.otf
  TripLog/TripLog/Source/Fonts/SCDream7.otf
  TripLog/TripLog/Source/Fonts/SCDream8.otf
  TripLog/TripLog/Source/Fonts/SCDream9.otf
  TripLog/TripLog/Source/Protocol/ViewModelType.swift
Labels: enhancement

#6 🚨[hotFix] 폰트 네임 수정
  TripLog/TripLog/Source/Extension/UIFont+Extension.swift
Labels: bug

#9 [Feat]-7-api&coredata
  TripLog/TripLog.xcodeproj/project.pbxproj
  TripLog/TripLog/Application/Info.plist
  TripLog/TripLog/Application/TripLog.xcdatamodeld/TripLog.xcdatamodel/contents
  TripLog/TripLog/Source/API&CoreData/Model/CurrencyEntity+CoreDataClass.swift
  TripLog/TripLog/Source/API&CoreData/Model/CurrencyEntity+CoreDataProperties.swift
  TripLog/TripLog/Source/API&CoreData/Model/CurrencyRate.swift
  TripLog/TripLog/Source/API&CoreData/Network/APIManager.swift
  TripLog/TripLog/Source/API&CoreData/Network/CoreDataManager.swift
  TripLog/TripLog/Source/Extension/Date+Extension.swift
  TripLog/TripLog/Source/Utility/APIInfo.swift
  TripLog/TripLogTests/CoreDataTests.swift
Labels: enhancement

#14 [Feat] Alert 매니저 구현
  TripLog/TripLog/Feat-Crois/AlertManager/AlertManager.swift
Labels: enhancement

#16 [Feat] 설정 탭 테이블뷰 셀 모델&데이터소스 구현
  TripLog/TripLog/Feat-Crois/SettingViewController/Model/SettingTableCellModel.swift
  TripLog/TripLog/Feat-Crois/SettingViewController/Model/SettingTableViewDataSource.swift
  TripLog/TripLog/Feat-Crois/SettingViewController/View/SettingViewController.swift
  TripLog/TripLog/Source/Assets/Assets.xcassets/SettingViewItem/Contents.json
  TripLog/TripLog/Source/Assets/Assets.xcassets/SettingViewItem/darkModeIcon.imageset/Contents.json
  TripLog/TripLog/Source/Assets/Assets.xcassets/SettingViewItem/darkModeIcon.imageset/item1.png
  TripLog/TripLog/Source/Assets/Assets.xcassets/SettingViewItem/mailIcon.imageset/Contents.json
  TripLog/TripLog/Source/Assets/Assets.xcassets/SettingViewItem/mailIcon.imageset/item3.png
  TripLog/TripLog/Source/Assets/Assets.xcassets/SettingViewItem/reviewIcon.imageset/Contents.json
  TripLog/TripLog/Source/Assets/Assets.xcassets/SettingViewItem/reviewIcon.imageset/item2.png
  TripLog/TripLog/Source/Assets/Assets.xcassets/SettingViewItem/versionIcon.imageset/Contents.json
  TripLog/TripLog/Source/Assets/Assets.xcassets/SettingViewItem/versionIcon.imageset/item4.png
Labels: enhancement

#22 [Feat] 다크모드 지원 스타일 시스템 구현
  TripLog/TripLog/Source/Assets/ColorAsseets.xcassets/CustomColors/Accent/Contents.json
  TripLog/TripLog/Source/Assets/ColorAsseets.xcassets/CustomColors/Accent/blue.colorset/Contents.json
  TripLog/TripLog/Source/Assets/ColorAsseets.xcassets/CustomColors/Background/Contents.json
  TripLog/TripLog/Source/Assets/ColorAsseets.xcassets/CustomColors/Background/background.colorset/Contents.json
  TripLog/TripLog/Source/Assets/ColorAsseets.xcassets/CustomColors/Background/detailBackground.colorset/Contents.json
  TripLog/TripLog/Source/Assets/ColorAsseets.xcassets/CustomColors/Border/Contents.json
  TripLog/TripLog/Source/Assets/ColorAsseets.xcassets/CustomColors/Border/border.colorset/Contents.json
  TripLog/TripLog/Source/Assets/ColorAsseets.xcassets/CustomColors/Border/darkBackground.colorset/Contents.json
  TripLog/TripLog/Source/Assets/ColorAsseets.xcassets/CustomColors/Border/plus.colorset/Contents.json
  TripLog/TripLog/Source/Assets/ColorAsseets.xcassets/CustomColors/Contents.json
  TripLog/TripLog/Source/Assets/ColorAsseets.xcassets/CustomColors/Text/Contents.json
  TripLog/TripLog/Source/Assets/ColorAsseets.xcassets/CustomColors/Text/textPlaceholder.colorset/Contents.json
  TripLog/TripLog/Source/Assets/ColorAsseets.xcassets/CustomColors/Text/textPrimary.colorset/Contents.json
  TripLog/TripLog/Source/Assets/ColorAsseets.xcassets/CustomColors/Text/textSecondary.colorset/Contents.json
  TripLog/TripLog/Source/Extension/TestViewController/TestViewController.swift
  TripLog/TripLog/Source/Extension/UIViewStyle+Extension.swift
Labels: enhancement

#10 [Feat]-3-topViewController
  TripLog/TripLog/Application/AppDelegate.swift
  TripLog/TripLog/Application/Base.lproj/LaunchScreen.storyboard
  TripLog/TripLog/Application/SceneDelegate.swift
  TripLog/TripLog/Assets/Assets.xcassets/SetIcon.imageset/Contents.json
  TripLog/TripLog/Assets/Assets.xcassets/SetIcon.imageset/터치영역.png
  TripLog/TripLog/Feat-Stone/Model/TestDummyData.swift
  TripLog/TripLog/Feat-Stone/View/ButtonStackView.swift
  TripLog/TripLog/Feat-Stone/View/ProgressView.swift
  TripLog/TripLog/Feat-Stone/View/TitleDateLabelView.swift
  TripLog/TripLog/Feat-Stone/View/TopViewController.swift
Labels: enhancement

#24 [Feat] 설정 탭 액션 구현
  TripLog/TripLog/Application/AppDelegate.swift
  TripLog/TripLog/Application/Base.lproj/LaunchScreen.storyboard
  TripLog/TripLog/Application/SceneDelegate.swift
  TripLog/TripLog/Feat-Crois/SettingViewController/Model/SettingTableCellModel.swift
  TripLog/TripLog/Feat-Crois/SettingViewController/View/SetTableViewCell.swift
  TripLog/TripLog/Feat-Crois/SettingViewController/View/SettingViewController.swift
  TripLog/TripLog/Source/AppHelpers/AlertManager.swift
  TripLog/TripLog/Source/AppHelpers/AppHelpers.swift
  TripLog/TripLog/Source/AppHelpers/ThemeManager.swift
Labels: bug, enhancement

#25 [Feat] 가계부 리스트 화면 구현
  TripLog/TripLog/Feat-Jeff/CashBookList/Model/CashBookListModel.swift
  TripLog/TripLog/Feat-Jeff/CashBookList/Service/PriceFormatModel.swift
  TripLog/TripLog/Feat-Jeff/CashBookList/View/AddCellView.swift
  TripLog/TripLog/Feat-Jeff/CashBookList/View/CashBookListViewController.swift
  TripLog/TripLog/Feat-Jeff/CashBookList/View/ListCollectionViewCell.swift
  TripLog/TripLog/Feat-Jeff/CashBookList/ViewModel/CashBookListViewModel.swift
Labels: enhancement

#49 [Fix] 런치스크린 버그 수정
  TripLog/TripLog/MainViewController.swift
Labels: bug

#50 [Feat] 모달뷰 가계부 수정 UI 로직 구현
  TripLog/TripLog/Feat-Crois/ModalViewController/Model/ModalViewState.swift
  TripLog/TripLog/Feat-Crois/ModalViewController/Model/TestCashBookData.swift
  TripLog/TripLog/Feat-Crois/ModalViewController/View/ModalDateView.swift
  TripLog/TripLog/Feat-Crois/ModalViewController/View/ModalView.swift
  TripLog/TripLog/Feat-Crois/ModalViewController/View/ModalViewController.swift
Labels: enhancement

#52 [Feat] 캘린더 커스텀 셀 UI 기본 구조 구현
  TripLog/TripLog/Feat-Jamong/ModalViewController/View/CalendarCustomCell.swift
  TripLog/TripLog/Feat-Jamong/ModalViewController/View/CalendarCustomHeaderView.swift
  TripLog/TripLog/Feat-Jamong/ModalViewController/View/CalendarView.swift
  TripLog/TripLog/Feat-Jamong/ModalViewController/View/CalendarViewController.swift
  TripLog/TripLog/Source/Extension/UIFont+Extension.swift
Labels: enhancement

#29 [Feat] "오늘 지출" UI 구현
  TripLog/TripLog.xcodeproj/project.pbxproj
  TripLog/TripLog/Assets/Assets.xcassets/SetIcon.imageset/Contents.json
  TripLog/TripLog/Assets/Assets.xcassets/SetIcon.imageset/터치영역.png
  TripLog/TripLog/Feat-Stone/Model/TestTodayDummyData.swift
  TripLog/TripLog/Feat-Stone/View/ProgressView.swift
  TripLog/TripLog/Feat-Stone/View/TitleDateLabelView.swift
  TripLog/TripLog/Feat-Stone/View/TodayView/ExpenseCell.swift
  TripLog/TripLog/Feat-Stone/View/TodayView/TodayVIewController.swift
Labels: enhancement
